In [34]:
f_in = open('shared_data/new york_anon_locationData_newcrawl.txt', 'r')
foursquare_venues = {}
for line in f_in:
	splits = line.split('*;*')
	venueid = splits[0]
	info = eval(splits[1])
	foursquare_venues[venueid] = info

In [37]:
# ny_venues = pd.DataFrame.from_dict(foursquare_venues, orient='index', 
#                        columns=['latitude', 'longitude', 'category', 'unique_users', 'total_check-ins', 'title'])
# ny_venues.to_csv('shared_data/ny_venues.csv', 
#                  columns=['latitude', 'longitude', 'category', 'unique_users', 'total_check-ins', 'title'])

In [3]:
import pandas as pd
transitions = pd.read_csv('shared_data/new york_placenet_transitions.txt', sep=',', names=['A_id', 'B_id','A_datetime', 'B_datetime'])
ny_venues = pd.read_csv('shared_data/ny_venues.csv', sep=',')

In [2]:
transitions.head()

A_id   B_id           A_datetime           B_datetime
0  34814  32616  2011-04-01 21:46:59  2011-04-03 23:25:17
1   6136  41982  2011-04-06 03:03:56  2011-04-06 03:22:48
2  41982  35981  2011-04-06 03:22:48  2011-04-07 18:00:53
3  35981   6701  2011-04-07 18:00:53  2011-04-07 18:01:06
4   6701  57814  2011-04-07 18:01:06  2011-04-08 22:38:26

In [4]:
ny_venues.head()

venue_id   latitude  longitude            category  unique_users  \
0     42889  40.760265 -73.989105             Italian           217   
1     57489  40.780704 -73.954704              Bakery          1291   
2     42890  40.663925 -74.118230         Video Store            60   
3     74771  40.739840 -73.991770  Corporate ' Office             6   
4     42891  40.786987 -73.807530        Other - Food            29   

   total_check-ins                 title  
0              291  Ristorante Da Rosina  
1             2231     Le Pain Quotidien  
2              186           Blockbuster  
3               12    Day & Night Office  
4               40           Erin's Isle

In [15]:
venues = {}
for index, row in ny_venues.iterrows():
    venues[row.venue_id] = row.to_dict()
    
    
    
    
    
    

In [17]:
venues[0]['latitude']

40.763992

In [4]:
print(max(ny_venues.latitude))
print(min(ny_venues.latitude))
print(max(ny_venues.longitude))
print(min(ny_venues.longitude))
# for index, row in ny_venues.iterrows():
#     print(row.latitude

40.99928
40.415005
-73.48129
-74.28631


In [10]:
from geopy import distance
from math import pi, cos


class Geometry:
    R_EARTH = 6371.0 
    
    #calculating new latitude in n meters 
    @staticmethod
    def _get_latitude(latitude, n_meters):
        if abs(latitude)>90:
            return 0
        dy = n_meters/1000
        return latitude  + (dy / Geometry.R_EARTH) * (180 / pi);
    
    #calculating new longtitude in n meters 
    @staticmethod
    def _get_longtitude(latitude, longitude, n_meters):
#         check real values
        if abs(latitude)>90 or abs(longitude)>180:
            return 0
        dx = n_meters/1000
        return longitude + (dx / Geometry.R_EARTH) * (180 / pi) / cos(latitude * pi/180);
    
    @staticmethod
    def get_places_around(center_coordinates, radius, venues):
#         circle area
        places_ids = []
        for index, row in venues.iterrows():
            dist = distance.distance(center_coordinates, (row.latitude, row.longitude)).m
            if dist<=radius:
                places_ids.append(row.venue_id)
        return places_ids
    
    def get_rect_points(center, size):
        radius = size/2
        
        # A-B
        # D-C
        a_lat = Geometry._get_latitude(center[0], radius)
        a_long = Geometry._get_longtitude(center[0], center[1], -radius)
        
        b_lat = Geometry._get_latitude(center[0], radius)
        b_long = Geometry._get_longtitude(center[0], center[1], radius)
        
        c_lat = Geometry._get_latitude(center[0], -radius)
        c_long = Geometry._get_longtitude(center[0], center[1], radius)
        
        d_lat = Geometry._get_latitude(center[0], -radius)
        d_long = Geometry._get_longtitude(center[0], center[1], -radius)
        
        coordinates = [(a_lat, a_long), (b_lat, b_long), (c_lat, c_long), (d_lat, d_long)]
        return coordinates
    
    def get_cell_centres:
        

In [12]:
Geometry.get_rect_points(center=(40, -73), size=200)

[(40.00089932160592, -73.00117398097981),
 (40.00089932160592, -72.99882601902019),
 (39.99910067839408, -72.99882601902019),
 (39.99910067839408, -73.00117398097981)]

In [23]:
distance.distance((40, 74), (40, 74.0025)).m

213.48464238941

In [ ]:
# from geometry import Geometry 
places = Geometry.get_places_around(center_coordinates=(40.760265,-73.989105), radius=500, venues=ny_venues)
print(places)

In [52]:
import numpy as np
lonMin = -74.1  # minimum longitude
lonMax = -73.7
lonStep = 0.01 # defines cell size
 
latMin = 40.6  # minimum latitude
latMax = 41.0
latStep = 0.01  # defines cell size
 
latLen = int((latMax - latMin) / latStep) + 1  # number of cells on the y-axis
lonLen = int((lonMax - lonMin) / lonStep) + 1  # number of cells on the x-axis

venues_grid=np.zeros((latLen, lonLen), dtype=np.ndarray)

for index, row in ny_venues.iterrows():
        lat = row.latitude
        longit = row.longitude
        # if outside the grid then ingore point
        if (lat < latMin) or (lat > latMax) or (longit < lonMin) or (longit > lonMax):
            continue
        cx = int((longit - lonMin) / lonStep)
        cy = int((lat - latMin) / latStep)        
        venues_grid[cy, cx]=np.append(venues_grid[cy, cx], row.venue_id)
            



In [12]:
import numpy as np
a = np.zeros((10, 10))

In [30]:
a = np.array([])

In [1]:
from feature_extractor import FeatureExtractor
import pandas as pd
transitions = pd.read_csv('shared_data/new york_placenet_transitions.txt', sep=',', names=['A_id', 'B_id','A_datetime', 'B_datetime'])
ny_venues = pd.read_csv('shared_data/ny_venues.csv', sep=',')
extractor = FeatureExtractor(ny_venues, transitions)
extractor.calculate_squares()

In [2]:
extractor.venues_grid[36]

array([array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([51661., 64976., 54656., 81138., 72815., 73925., 75841., 81401.,
       37537., 39780., 41784.]),
       array([62647., 23337., 30373., 77661.]),
       array([  111., 45096., 14375., 78182.]),
       array([82218., 38532., 21308., 66912., 24938., 31060., 39018., 42707.]),
       array([], dtype=float64), array([], dtype=float64),
     

In [6]:
import numpy as np
a = np.zeros((10, 10), dtype=np.ndarray)
for i in range(10):
    for j in range(10):
        a[i][j] = np.array([])
a[0,1]

array([], dtype=float64)

In [7]:
a[0,1]=np.array([11])

In [8]:
a

array([[array([], dtype=float64), array([11]), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64)],
       [array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64)],
       [array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64)],
       [array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=