In [34]:
f_in = open('shared_data/new york_anon_locationData_newcrawl.txt', 'r')
foursquare_venues = {}
for line in f_in:
	splits = line.split('*;*')
	venueid = splits[0]
	info = eval(splits[1])
	foursquare_venues[venueid] = info

In [37]:
# ny_venues = pd.DataFrame.from_dict(foursquare_venues, orient='index', 
#                        columns=['latitude', 'longitude', 'category', 'unique_users', 'total_check-ins', 'title'])
# ny_venues.to_csv('shared_data/ny_venues.csv', 
#                  columns=['latitude', 'longitude', 'category', 'unique_users', 'total_check-ins', 'title'])

In [3]:
import pandas as pd
transitions = pd.read_csv('shared_data/new york_placenet_transitions.txt', sep=',', names=['A_id', 'B_id','A_datetime', 'B_datetime'])
ny_venues = pd.read_csv('shared_data/ny_venues.csv', sep=',')

In [2]:
transitions.head()

A_id   B_id           A_datetime           B_datetime
0  34814  32616  2011-04-01 21:46:59  2011-04-03 23:25:17
1   6136  41982  2011-04-06 03:03:56  2011-04-06 03:22:48
2  41982  35981  2011-04-06 03:22:48  2011-04-07 18:00:53
3  35981   6701  2011-04-07 18:00:53  2011-04-07 18:01:06
4   6701  57814  2011-04-07 18:01:06  2011-04-08 22:38:26

In [4]:
ny_venues.head()

venue_id   latitude  longitude            category  unique_users  \
0     42889  40.760265 -73.989105             Italian           217   
1     57489  40.780704 -73.954704              Bakery          1291   
2     42890  40.663925 -74.118230         Video Store            60   
3     74771  40.739840 -73.991770  Corporate ' Office             6   
4     42891  40.786987 -73.807530        Other - Food            29   

   total_check-ins                 title  
0              291  Ristorante Da Rosina  
1             2231     Le Pain Quotidien  
2              186           Blockbuster  
3               12    Day & Night Office  
4               40           Erin's Isle

In [15]:
venues = {}
for index, row in ny_venues.iterrows():
    venues[row.venue_id] = row.to_dict()
    
    
    
    
    
    

In [17]:
venues[0]['latitude']

40.763992

In [4]:
print(max(ny_venues.latitude))
print(min(ny_venues.latitude))
print(max(ny_venues.longitude))
print(min(ny_venues.longitude))
# for index, row in ny_venues.iterrows():
#     print(row.latitude

40.99928
40.415005
-73.48129
-74.28631


In [10]:
from geopy import distance
from math import pi, cos


class Geometry:
    R_EARTH = 6371.0 
    
    #calculating new latitude in n meters 
    @staticmethod
    def _get_latitude(latitude, n_meters):
        if abs(latitude)>90:
            return 0
        dy = n_meters/1000
        return latitude  + (dy / Geometry.R_EARTH) * (180 / pi);
    
    #calculating new longtitude in n meters 
    @staticmethod
    def _get_longtitude(latitude, longitude, n_meters):
#         check real values
        if abs(latitude)>90 or abs(longitude)>180:
            return 0
        dx = n_meters/1000
        return longitude + (dx / Geometry.R_EARTH) * (180 / pi) / cos(latitude * pi/180);
    
    @staticmethod
    def get_places_around(center_coordinates, radius, venues):
#         circle area
        places_ids = []
        for index, row in venues.iterrows():
            dist = distance.distance(center_coordinates, (row.latitude, row.longitude)).m
            if dist<=radius:
                places_ids.append(row.venue_id)
        return places_ids
    
    def get_rect_points(center, size):
        radius = size/2
        
        # A-B
        # D-C
        a_lat = Geometry._get_latitude(center[0], radius)
        a_long = Geometry._get_longtitude(center[0], center[1], -radius)
        
        b_lat = Geometry._get_latitude(center[0], radius)
        b_long = Geometry._get_longtitude(center[0], center[1], radius)
        
        c_lat = Geometry._get_latitude(center[0], -radius)
        c_long = Geometry._get_longtitude(center[0], center[1], radius)
        
        d_lat = Geometry._get_latitude(center[0], -radius)
        d_long = Geometry._get_longtitude(center[0], center[1], -radius)
        
        coordinates = [(a_lat, a_long), (b_lat, b_long), (c_lat, c_long), (d_lat, d_long)]
        return coordinates
    
    def get_cell_centres:
        

In [12]:
Geometry.get_rect_points(center=(40, -73), size=200)

[(40.00089932160592, -73.00117398097981),
 (40.00089932160592, -72.99882601902019),
 (39.99910067839408, -72.99882601902019),
 (39.99910067839408, -73.00117398097981)]

In [23]:
distance.distance((40, 74), (40, 74.0025)).m

213.48464238941

In [ ]:
# from geometry import Geometry 
places = Geometry.get_places_around(center_coordinates=(40.760265,-73.989105), radius=500, venues=ny_venues)
print(places)

In [52]:
import numpy as np
lonMin = -74.1  # minimum longitude
lonMax = -73.7
lonStep = 0.01 # defines cell size
 
latMin = 40.6  # minimum latitude
latMax = 41.0
latStep = 0.01  # defines cell size
 
latLen = int((latMax - latMin) / latStep) + 1  # number of cells on the y-axis
lonLen = int((lonMax - lonMin) / lonStep) + 1  # number of cells on the x-axis

venues_grid=np.zeros((latLen, lonLen), dtype=np.ndarray)

for index, row in ny_venues.iterrows():
        lat = row.latitude
        longit = row.longitude
        # if outside the grid then ingore point
        if (lat < latMin) or (lat > latMax) or (longit < lonMin) or (longit > lonMax):
            continue
        cx = int((longit - lonMin) / lonStep)
        cy = int((lat - latMin) / latStep)        
        venues_grid[cy, cx]=np.append(venues_grid[cy, cx], row.venue_id)
            



In [12]:
import numpy as np
a = np.zeros((10, 10))

In [30]:
a = np.array([])

In [1]:
from feature_extractor import FeatureExtractor
import pandas as pd
transitions = pd.read_csv('shared_data/new york_placenet_transitions.txt', sep=',', names=['A_id', 'B_id','A_datetime', 'B_datetime'])
ny_venues = pd.read_csv('shared_data/ny_venues.csv', sep=',')
extractor = FeatureExtractor(ny_venues, transitions)
extractor.calculate_squares()

In [2]:
extractor.venues_grid[36]

array([array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([], dtype=float64), array([], dtype=float64),
       array([51661., 64976., 54656., 81138., 72815., 73925., 75841., 81401.,
       37537., 39780., 41784.]),
       array([62647., 23337., 30373., 77661.]),
       array([  111., 45096., 14375., 78182.]),
       array([82218., 38532., 21308., 66912., 24938., 31060., 39018., 42707.]),
       array([], dtype=float64), array([], dtype=float64),
     

In [6]:
import numpy as np
a = np.zeros((10, 10), dtype=np.ndarray)
for i in range(10):
    for j in range(10):
        a[i][j] = np.array([])
a[0,1]

array([], dtype=float64)

In [7]:
a[0,1]=np.array([11])

In [8]:
a

array([[array([], dtype=float64), array([11]), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64)],
       [array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64)],
       [array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=float64)],
       [array([], dtype=float64), array([], dtype=float64),
        array([], dtype=float64), array([], dtype=

In [21]:
b = [1, 2, 3]
mean(b)

NameError: name 'mean' is not defined

In [23]:
c=[]
len(c)

0

In [24]:
data = pd.read_csv('features.csv')

In [25]:
data.head()

Unnamed: 0   cy   cx  latitude  longitude  density  neighbors_entropy  \
0           0  0.0  0.0     40.65     -74.05      0.0           0.000000   
1           1  0.0  1.0     40.65     -74.04      0.0           0.000000   
2           2  0.0  2.0     40.65     -74.03      1.0           0.000000   
3           3  0.0  3.0     40.65     -74.02      8.0           2.405639   
4           4  0.0  4.0     40.65     -74.01     25.0           4.665169   

   competitiveness  average_check_ins  
0             0.00                0.0  
1             0.00                0.0  
2             0.00                0.0  
3             0.00                0.0  
4            -0.04                0.0

In [26]:
data[data.average_check_ins!=0]

Unnamed: 0    cy    cx  latitude  longitude  density  neighbors_entropy  \
56            56   2.0   4.0   40.6550     -74.01     22.0           6.528213   
62            62   2.0  10.0   40.6550     -73.95     23.0           4.997912   
67            67   2.0  15.0   40.6550     -73.90      4.0           2.000000   
139          139   5.0   9.0   40.6625     -73.96     34.0           5.112171   
189          189   7.0   7.0   40.6675     -73.98     40.0           7.378406   
195          195   7.0  13.0   40.6675     -73.92     21.0           4.715395   
267          267  10.0   7.0   40.6750     -73.98     87.0           7.269041   
300          300  11.0  14.0   40.6775     -73.91     10.0           4.982892   
345          345  13.0   7.0   40.6825     -73.98     82.0           6.650552   
351          351  13.0  13.0   40.6825     -73.92     11.0           5.611746   
386          386  14.0  22.0   40.6850     -73.83     33.0           5.292199   
396          396  15.0   6.0   40.6875     -73.99    166.0           6.653392   
410          410  15.0  20.0   40.6875     -73.85     14.0           4.079309   
422          422  16.0   6.0   40.6900     -73.99    177.0           8.051955   
434          434  16.0  18.0   40.6900     -73.87     16.0           3.750000   
447          447  17.0   5.0   40.6925     -74.00    167.0           7.913047   
449          449  17.0   7.0   40.6925     -73.98     38.0           6.602353   
515          515  19.0  21.0   40.6975     -73.84     21.0           4.315761   
523          523  20.0   3.0   40.7000     -74.02     47.0           6.229221   
530          530  20.0  10.0   40.7000     -73.95     45.0           5.152675   
534          534  20.0  14.0   40.7000     -73.91     50.0           5.096342   
543          543  20.0  23.0   40.7000     -73.82     25.0           4.429610   
549          549  21.0   3.0   40.7025     -74.02    226.0           9.059255   
550          550  21.0   4.0   40.7025     -74.01    109.0           8.018431   
559          559  21.0  13.0   40.7025     -73.92     43.0           5.209268   
575          575  22.0   3.0   40.7050     -74.02    258.0           7.002543   
576          576  22.0   4.0   40.7050     -74.01    389.0           8.357899   
601          601  23.0   3.0   40.7075     -74.02    243.0           8.468380   
602          602  23.0   4.0   40.7075     -74.01    306.0           8.053180   
628          628  24.0   4.0   40.7100     -74.01    222.0           8.297865   
...          ...   ...   ...       ...        ...      ...                ...   
1439        1439  55.0   9.0   40.7875     -73.96     37.0           5.508777   
1453        1453  55.0  23.0   40.7875     -73.82     40.0           7.396213   
1456        1456  56.0   0.0   40.7900     -74.05     12.0           7.302005   
1466        1466  56.0  10.0   40.7900     -73.95     62.0           6.573309   
1568        1568  60.0   8.0   40.8000     -73.97    115.0           9.673325   
1569        1569  60.0   9.0   40.8000     -73.96     47.0           5.676246   
1570        1570  60.0  10.0   40.8000     -73.95     47.0           5.702738   
1597        1597  61.0  11.0   40.8025     -73.94     50.0           7.534052   
1622        1622  62.0  10.0   40.8050     -73.95     79.0           8.176637   
1642        1642  63.0   4.0   40.8075     -74.01     22.0           5.200212   
1667        1667  64.0   3.0   40.8100     -74.02     10.0           2.846439   
1725        1725  66.0   9.0   40.8150     -73.96     31.0           6.358776   
1726        1726  66.0  10.0   40.8150     -73.95     54.0           5.935896   
1729        1729  66.0  13.0   40.8150     -73.92     47.0           5.518588   
1731        1731  66.0  15.0   40.8150     -73.90     22.0           4.669586   
1751        1751  67.0   9.0   40.8175     -73.96     38.0           5.608289   
1778        1778  68.0  10.0   40.8200     -73.95     35.0           7.016607   
1781        1781  68.0  13.0   40.820